### ISSUE TITLE
Refractoring code

### ISSUE THREAD

**Issue by Huy-Ngo** [dinhanhx/Automatic_Speaker_Recognition#1]
I find that the code in mfcc_gmm_func.py is hard to read because:

- Overcommenting: some comments are redundant and distracting (e.g. it's quite obvious that `wavfile` is for handling wav file). In addition, I think comments are more helpful where the imported function/module is used than where it's imported.
- Function docstrings are unconventionally placed: They're put as comments before function declaration

Since everyone has their own tasks now, I'll try to do this without affecting its usage

**Comment by dinhanhx** [comment]
That fast!

**Comment by Huy-Ngo** [comment]
Well, I need that for the report.
